name: Build and Push Docker Images to AWS ECR

on:
  push:
    paths:
      - src/**
      - .github/**
    branches:
      - main # Trigger the workflow on push to the main branch


jobs:
  get_version:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}
    
    outputs:
      image_tag: ${{ steps.increment-git-tag.outputs.git-tag }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/version_update.sh -v minor

  build_and_push:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}

    needs: get_version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
      
      - name: Build and push Docker image to ECR
        env:
          IMAGE_TAG: ${{ needs.get_version.outputs.image_tag }}
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:$IMAGE_TAG