name: Build and Push Docker Images to AWS ECR

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch


jobs:
  get_version:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}
    
    outputs:
      image_tag: ${{ steps.increment-git-tag.outputs.git-tag }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/version_update.sh -v minor
