name: Build and Push Docker Images to AWS ECR

on:
  push:
    paths:
      - src/**
      - .github/**
    branches:
      - main # Trigger the workflow on push to the main branch


jobs:
  build_and_push:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Testing Command
        run: echo "Hello World"
