name: Build and Push Docker Images to AWS ECR

on:
  push:
    paths:
      - src/**
      - .github/**
      - Dockerfile
    branches:
      - main # Trigger the workflow on push to the main branch


jobs:
  terraform:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan