name: Build and Push Docker Images to AWS ECR

on:
  push:
    paths:
      - src/**
      - .github/**
      - Dockerfile
    branches:
      - main # Trigger the workflow on push to the main branch


jobs:
  update_version:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update image version in k8s manifests
        id: bump-version
        env:
          IMAGE_TAG: v0.10.0
        run: |
          sed -i "s/\(container_image = \"671415945235.dkr.ecr.us-east-1.amazonaws.com\/blockchain-analyzer:\)[^\"]*/\1$IMAGE_TAG/" terraform/terraform.tfvars
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update image to $IMAGE_TAG"
          git push