name: Build and Push Docker Images to AWS ECR

on:
  push:
    paths:
      - src/**
      - .github/**
      - Dockerfile
    branches:
      - main # Trigger the workflow on push to the main branch


jobs:
  get_version:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}
    
    outputs:
      image_tag: ${{ steps.increment-git-tag.outputs.git-tag }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/version_update.sh -v minor

  build_and_push:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}

    needs: get_version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
      
      - name: Build and push Docker image to ECR
        env:
          IMAGE_TAG: ${{ needs.get_version.outputs.image_tag }}
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:$IMAGE_TAG

  update_version:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}
    
    needs: ["get_version", "build_and_push"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update image version in k8s manifests
        id: bump-version
        env:
          IMAGE_TAG: ${{ needs.get_version.outputs.image_tag }}
        run: |
          sed -i "s/\(container_image = \"671415945235.dkr.ecr.us-east-1.amazonaws.com\/blockchain-analyzer:\)[^\"]*/\1$IMAGE_TAG/" terraform/terraform.tfvars
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update image to $IMAGE_TAG"
          git push

  terraform:
    runs-on: 
      - codebuild-image-builder-${{ github.run_id }}-${{ github.run_attempt }}

    defaults:
      run:
        working-directory: terraform

    needs: ["update_version"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan
      
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply --auto-approve